name: renegade
version: '${project.version}'
main: org.hey.renegade.Renegade
api-version: '1.20'
commands:
  allow:
    description: wowza
    usage: /allow name ip
  deny:
    description: yowza
    usage: /deny name